### ISSUE TITLE
Incompatibility with MarkdownEditing

### ISSUE THREAD

**Issue by orschiro** [leonid-shevtsov/ClickableUrls_SublimeText#11]
Hi there,

Thanks for your plugin. I noticed that there seems to be an incompatibility with [MarkdownEditing](https://github.com/SublimeText-Markdown/MarkdownEditing).

URLs are not underlined, nor are they clickable.

Something can be done to make both compatible?

Thanks!

![urls](https://f.cloud.github.com/assets/170947/2429083/a3a7a4f0-ac6a-11e3-896b-27518b2a41f3.png)

**Comment by leonid-shevtsov** [comment]
I have this plugin and sure enough it applies its own styles to URLs, that override the ClickableUrls styles. Adding this to "Known issues". Thanks!

**Comment by orschiro** [comment]
Thanks for your response!
