### ISSUE TITLE
Conflict with `Goto Documentation`

### ISSUE THREAD

**Issue by cvsguimaraes** [leonid-shevtsov/ClickableUrls_SublimeText#12]
It seems that this package is conflicting with [Goto Documentation](https://github.com/kemayo/sublime-text-2-goto-documentation).

For example, when I press the binded key to see the documentation of a function (with diferrent key bindings for each package of course) nothing happens and I receive the following message under the sublime console:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
TypeError: run() got an unexpected keyword argument 'url'
```

I'm currently with Sublime 3059.

**Comment by leonid-shevtsov** [comment]
Can't reproduce on recent versions - closing this for now. Please reopen if the issue persists.
