### ISSUE TITLE
How can I make UNC's also clickable?

### ISSUE THREAD

**Issue by mkanet** [leonid-shevtsov/ClickableUrls_SublimeText#14]
Hi, Im really amazed you were able to figure out a way to make URL's clickable.  I was hoping you knew enough about ST3's API to know how to also make UNC paths clickable (opening up the default OS file explorer using the UNC path).  Maybe you could either enhance this plugin or show me how to make a separate plugin that does this?  I'm sure many people would take advantage of this functionality if it existed.  Thanks so much for all your effort for making such a great plugin.

**Comment by leonid-shevtsov** [comment]
If you haven't found such a plugin yet I'm willing to try this.
