### ISSUE TITLE
Question: When using "Alt+MouseClick"

### ISSUE THREAD

**Issue by mkanet** [leonid-shevtsov/ClickableUrls_SublimeText#15]
You were able to help me to configure ClickableUrls so I can use Alt+MouseClick.

However, when I press Alt+MouseClick, the Sublime Text Menus become visible.  The menus do not hide until I manually press the "Alt" key once.  Or, I have to wait until I restart Sublime Text.

Is it possible to enhance this addon so the Sublime Text menus are only visible briefly after pressing Alt+MouseClick.  Maybe automate an "Alt" keypress after ClickableUrls is executed?

Ideally, I think using _Ctrl+MouseClick_ would be best.  @leonid-shevtsov: Are there any changes to the the latest ST3 dev builds yet that let you use Ctrl+MouseClick instead of Alt+MouseClick? Or, the ability to use the color BLUE for the hyperlink text color?

**Comment by leonid-shevtsov** [comment]
the state of events is:

* you still can't change the text color apart from patching the syntax file to recognize urls
* you can bind the to ctrl+mouseclick, go to `preferences -> package settings -> clickable urls -> mouse bindings` and specify

        [
            { "button": "button1", "modifiers": ["option"], "press_command": "open_url" }
        ]
