### ISSUE TITLE
Urls aren't detected when ST2/ST3 "Remember Open Files" is enabled

### ISSUE THREAD

**Issue by mkanet** [leonid-shevtsov/ClickableUrls_SublimeText#16]
Every time Sublime Text restarts, none of the URLs are detected in any of the Sublime Text tabs.  The only way to see clickable urls, is by manually reopening each document or pressing any key (ie, spacebar) to make a change to each document that was automatically opened by ST.

@leonid-shevtsov, maybe there's a clever way to work around the Sublime Text "Remember Open Files" feature?

Could you please

**Comment by leonid-shevtsov** [comment]
Version 1.3.0 should handle this, please reopen this issue if it persists.
