### ISSUE TITLE
Conflict with "Package Control: Discover Package" command

### ISSUE THREAD

**Issue by pribilinskiy** [leonid-shevtsov/ClickableUrls_SublimeText#17]
After invoking the `Package Control: Discover Package` command nothing happens.
Following is captured from the console.
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3 Portable\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
TypeError: run() got an unexpected keyword argument 'url'
```

Problem is fixed only after removing **Clickable URLs** package

Windows 8.1 x64, ST b3062

**Comment by leonid-shevtsov** [comment]
This happened because I had overridden the built-in `open_url` command. Fixed in v1.3.0 by renaming the Clickable URLs command to `open_url_under_cursor`.
