### ISSUE TITLE
Actually make URIs "clickable"

### ISSUE THREAD

**Issue by FichteFoll** [leonid-shevtsov/ClickableUrls_SublimeText#2]
You can define `.sublime-mousemap` bindings, you just need to assign a command to an action like you do with keybindings.

Here are a few examples: [Default (Linux).sublime-mousmap](https://github.com/Kronuz/SublimeCodeIntel/blob/master/Default%20%28Linux%29.sublime-mousemap), [some comment of mine](https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/127#issuecomment-6353854).

**Comment by rhoconlinux** [comment]
Hello everyone. I spent some time in this so I'm sharing it. In Linux, you can run the following one-line command to setup the clickable urls within Sublime. 

<pre>
echo '[' > ~/.config/sublime-text-3/Packages/User/Default\ \(Linux\).sublime-mousemap && echo '{ "button": "button1", "modifiers": ["Ctrl"], "press_command": "open_url" },' >> ~/.config/sublime-text-3/Packages/User/Default\ \(Linux\).sublime-mousemap && echo '[' >> ~/.config/sublime-text-3/Packages/User/Default\ \(Linux\).sublime-mousemap
</pre>

You **will have to** click on the url and to open it, ctrl+click. 

Cheers! :)

**Comment by Nabawe** [comment]
Hi for me to work I changed:
`Ctrl` to `ctrl`
`open_url` to `open_url_under_cursor`

For Windows change `(Linux)` to `(Windows)` or for a general default erase `(Linux)` and the **preceding white space**.


`echo '[' > ~/.config/sublime-text-3/Packages/User/Default\ \(Linux\).sublime-mousemap && echo '{ "button": "button1", "modifiers": ["ctrl"], "press_command": "open_url_under_cursor" },' >> ~/.config/sublime-text-3/Packages/User/Default\ \(Linux\).sublime-mousemap && echo '[' >> ~/.config/sublime-text-3/Packages/User/Default\ \(Linux\).sublime-mousemap`

**Comment by girtsf** [comment]
FWIW, this worked for me (Sublime 3.0, build 3143 on macOS):
```
[{ "button": "button1", "modifiers": ["command"], "press_command": "open_url_under_cursor" }]
```

**Comment by AmjadHD** [comment]
That doesn't work for me, if the cursor is not already on the url, but this does:
```json
{
  "button": "button1",
  "count": 1,
  "modifiers": ["alt"],
  "command": "open_url_under_cursor",
  "press_command": "drag_select",
}
```

**Comment by john-cj** [comment]
I think @AmjadHD version could be added to master. A lot of people use mouse, actually :smile:

**Comment by Marco-Sulla** [comment]
> That doesn't work for me, if the cursor is not already on the url, but this does:
> 
> ```json
> {
>   "button": "button1",
>   "count": 1,
>   "modifiers": ["alt"],
>   "command": "open_url_under_cursor",
>   "press_command": "drag_select",
> }
> ```

This does not work for me on Linux and Sublime 3. [Nabawe](https://github.com/leonid-shevtsov/ClickableUrls_SublimeText/issues/2#issuecomment-221382432)'s solution works for me, even if I added `ctrl` only.

**Comment by FichteFoll** [comment]
You may also be interested in https://github.com/jfcherng/Sublime-OpenUri (a fork of https://github.com/vicke4/open_in_browser), which shows clickable phantom views that you can click on next to each url and also has lots of settings.

**Comment by lwilli** [comment]
Combining [girtsf's answer](https://github.com/leonid-shevtsov/ClickableUrls_SublimeText/issues/2#issuecomment-354023502) with [AmjadHD's answer](https://github.com/leonid-shevtsov/ClickableUrls_SublimeText/issues/2#issuecomment-354659035) did the trick for me in Sublime 4126 on macOS, which preserves the "drag_select" feature while also supporting opening links with one click (even when the cursor is elsewhere). Thanks!

```
[{
  "button": "button1",
  "count": 1,
  "modifiers": ["alt"],
  "command": "open_url_under_cursor",
  "press_command": "drag_select",
}]

```
