### ISSUE TITLE
Support non-ASCII characters in URLs

### ISSUE THREAD

**Issue by Kristinita** [leonid-shevtsov/ClickableUrls_SublimeText#28]
Здравствуйте. Когда в URL содержится кириллица, при клике на <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Enter</kbd>, ссылки открываются до части, где начинаются кириллические символы. Т.е. в браузере откроется не `http://www.dmoz.org/World/Russian/Компьютеры/Новости_и_СМИ/)` , а `http://www.dmoz.org/World/Russian/` . Планируете ли Вы вводить поддержку кириллицы? Спасибо.

![Пример работы ClickableUrls](http://pokit.org/get/img/52ca0fbff3ed1d83d39a6c42acb8304d.jpg)

**Comment by leonid-shevtsov** [comment]
Thanks, it does make sense to enhance the regex to support non-ASCII urls.
