### ISSUE TITLE
ST2: Link not clickable or underlined

### ISSUE THREAD

**Issue by mhulse** [leonid-shevtsov/ClickableUrls_SublimeText#3]
The keyboard shortcut works out of the box, but I don't see an underline and I'm not sure how to just make it so I can click on the links to open the URL (vs. use keyboard command).

Also, I don't see anything related to this plugin under the <kbd>Package Settings</kbd> menu. Are there supposed to be any package settings for this plugin?

Any tips? :+1:

**Comment by leonid-shevtsov** [comment]
As it happens, I've fixed this error just now in v1.3.0
