### ISSUE TITLE
"UrlHighlighter: ignoring view with 214 URLs"

### ISSUE THREAD

**Issue by 315234** [leonid-shevtsov/ClickableUrls_SublimeText#30]
Could this restriction be removed?

**Comment by 315234** [comment]
Never mind, found the appropriate setting.

**Comment by winternet-studio** [comment]
Where did you find that setting?

**Comment by winternet-studio** [comment]
For anyone else coming here the setting is `max_url_limit`, so add something like this to your package user settings:

```
{
	"max_url_limit": 500
}
```
