### ISSUE TITLE
Actually make URIs "clickable" & hyperlink text color

### ISSUE THREAD

**Issue by mkanet** [leonid-shevtsov/ClickableUrls_SublimeText#6]
Follow the instructions on how to make the URI's clickable.  However, I would like to use control+mouseclick instead of the alt+mouseclick.  How can I do that?

Also, how can I make it so clickable URI text has the color blue instead of the default text color?

**Comment by leonid-shevtsov** [comment]
>Is it possible to highlight the URLs with a different color using a TMLanguage file and respective colors from my custom color scheme? 

Sublime Text doesn't let you change the text color of a region or change its scope programmatically. So the only way to highlight text is make the syntax file recognize URLs and assign the proper scope to them.
