### ISSUE TITLE
ST3, Windows, Browser is not foreground

### ISSUE THREAD

**Issue by pribilinskiy** [leonid-shevtsov/ClickableUrls_SublimeText#9]
After invoking the command SublimeText window remains in focus and the link is opened in the Chrome browser in the background.

Previously the browser was focusing correctly.

Any thoughts? Is that happens because of a Chrome browser update?

**Comment by leonid-shevtsov** [comment]
I still can't reproduce this issue, but I found that you can pass a command line instead of the browser's identifier and that gives more control over behavior (see the README for details)
